"""station qc flag

Revision ID: 4398c3422d4f
Revises: ddc1eaf7f63b
Create Date: 2026-10-08 18:35:24.429388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4398c3422d4f'
down_revision: Union[str, Sequence[str], None] = 'ddc1eaf7f63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('qc_ok', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('stations', sa.Column('qc_reason', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'qc_reason')
    op.drop_column('stations', 'qc_ok')
    # ### end Alembic commands ###
