"""initial schema

Revision ID: b6b514e3f0ab
Revises: 
Create Date: 2026-10-08 16:57:14.462888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b514e3f0ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('coverage_label', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('is_holdout', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('trained_on_splits', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('county', sa.String(length=40), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('coverage_class', sa.String(length=16), nullable=False),
    sa.Column('nearest_water_km', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('hand_depth_m', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('imperviousness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exposure_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=16), nullable=False),
    sa.Column('osm_id', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exposure_assets_zone_id'), 'exposure_assets', ['zone_id'], unique=False)
    op.create_table('flood_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=40), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('date_is_collection', sa.Boolean(), nullable=False),
    sa.Column('zone_id', sa.String(length=16), nullable=True),
    sa.Column('county', sa.String(length=40), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.Column('flood_depth', sa.String(length=32), nullable=True),
    sa.Column('affected_area', sa.String(length=32), nullable=True),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_flood_observations_obs_date'), 'flood_observations', ['obs_date'], unique=False)
    op.create_index(op.f('ix_flood_observations_zone_id'), 'flood_observations', ['zone_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=16), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('issue_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_h', sa.Integer(), nullable=False),
    sa.Column('depth_q10', sa.Float(), nullable=False),
    sa.Column('depth_q50', sa.Float(), nullable=False),
    sa.Column('depth_q90', sa.Float(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_issue_ts'), 'forecasts', ['issue_ts'], unique=False)
    op.create_index(op.f('ix_forecasts_zone_id'), 'forecasts', ['zone_id'], unique=False)
    op.create_table('ranking_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('issue_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('ranked_zone_ids_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('zone_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('var', 'name')
    )
    op.create_table('dynamic_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('availability_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('interpolated_value', sa.Float(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'ts')
    )
    op.create_index(op.f('ix_dynamic_features_station_id'), 'dynamic_features', ['station_id'], unique=False)
    op.create_index(op.f('ix_dynamic_features_ts'), 'dynamic_features', ['ts'], unique=False)
    op.create_table('risk_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('onset_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onset_window', sa.JSON(), nullable=True),
    sa.Column('peak_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_window', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_output_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rendered_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_output_id'], ['risk_outputs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_output_id')
    )
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_output_id', sa.Integer(), nullable=False),
    sa.Column('driver_json', sa.JSON(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['risk_output_id'], ['risk_outputs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_output_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explanations')
    op.drop_table('alerts')
    op.drop_table('risk_outputs')
    op.drop_index(op.f('ix_dynamic_features_ts'), table_name='dynamic_features')
    op.drop_index(op.f('ix_dynamic_features_station_id'), table_name='dynamic_features')
    op.drop_table('dynamic_features')
    op.drop_table('stations')
    op.drop_table('ranking_runs')
    op.drop_index(op.f('ix_forecasts_zone_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_issue_ts'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_flood_observations_zone_id'), table_name='flood_observations')
    op.drop_index(op.f('ix_flood_observations_obs_date'), table_name='flood_observations')
    op.drop_table('flood_observations')
    op.drop_index(op.f('ix_exposure_assets_zone_id'), table_name='exposure_assets')
    op.drop_table('exposure_assets')
    op.drop_table('zones')
    op.drop_table('model_runs')
    op.drop_table('events')
    op.drop_table('regions')
    # ### end Alembic commands ###
