"""zone_stations

Revision ID: ddc1eaf7f63b
Revises: b6b514e3f0ab
Create Date: 2026-10-08 18:30:35.817130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc1eaf7f63b'
down_revision: Union[str, Sequence[str], None] = 'b6b514e3f0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_stations',
    sa.Column('zone_id', sa.String(length=16), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('var', sa.String(length=8), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('zone_id', 'station_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_stations')
    # ### end Alembic commands ###
